import type { Player, PlayerProfile, Team } from '../domain/types.js';

export const DEMO_TEAM: Team = {
  id: 'metro-city-meteors',
  name: 'Metro City Meteors',
  abbreviation: 'MCM',
};

export const DEMO_PLAYERS: readonly Player[] = [
  { id: 'jordan-vega', name: 'Jordan Vega', teamId: DEMO_TEAM.id, position: 'PG' },
  { id: 'malik-rhodes', name: 'Malik Rhodes', teamId: DEMO_TEAM.id, position: 'SG' },
  { id: 'eli-mercer', name: 'Eli Mercer', teamId: DEMO_TEAM.id, position: 'SF' },
  { id: 'theo-grant', name: 'Theo Grant', teamId: DEMO_TEAM.id, position: 'PF' },
  { id: 'andre-okafor', name: 'Andre Okafor', teamId: DEMO_TEAM.id, position: 'C' },
  { id: 'nico-park', name: 'Nico Park', teamId: DEMO_TEAM.id, position: 'PG' },
  { id: 'samir-cole', name: 'Samir Cole', teamId: DEMO_TEAM.id, position: 'SG' },
  { id: 'darius-knox', name: 'Darius Knox', teamId: DEMO_TEAM.id, position: 'SF/PF' },
  { id: 'owen-price', name: 'Owen Price', teamId: DEMO_TEAM.id, position: 'PF/C' },
  { id: 'luca-hayes', name: 'Luca Hayes', teamId: DEMO_TEAM.id, position: 'SF' },
];

export const DEMO_PROFILES: readonly PlayerProfile[] = [
  {
    playerId: 'jordan-vega',
    shooting: 92,
    creation: 94,
    playmaking: 88,
    rebounding: 40,
    perimeterDefense: 78,
    interiorDefense: 25,
    switchability: 75,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
  {
    playerId: 'malik-rhodes',
    shooting: 88,
    creation: 76,
    playmaking: 70,
    rebounding: 52,
    perimeterDefense: 82,
    interiorDefense: 40,
    switchability: 80,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
  {
    playerId: 'eli-mercer',
    shooting: 84,
    creation: 68,
    playmaking: 72,
    rebounding: 65,
    perimeterDefense: 86,
    interiorDefense: 58,
    switchability: 88,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
  {
    playerId: 'theo-grant',
    shooting: 76,
    creation: 55,
    playmaking: 60,
    rebounding: 87,
    perimeterDefense: 70,
    interiorDefense: 82,
    switchability: 78,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
  {
    playerId: 'andre-okafor',
    shooting: 42,
    creation: 38,
    playmaking: 55,
    rebounding: 94,
    perimeterDefense: 52,
    interiorDefense: 95,
    switchability: 60,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
  {
    playerId: 'nico-park',
    shooting: 79,
    creation: 83,
    playmaking: 84,
    rebounding: 45,
    perimeterDefense: 68,
    interiorDefense: 30,
    switchability: 66,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
  {
    playerId: 'samir-cole',
    shooting: 91,
    creation: 54,
    playmaking: 58,
    rebounding: 48,
    perimeterDefense: 75,
    interiorDefense: 35,
    switchability: 70,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
  {
    playerId: 'darius-knox',
    shooting: 66,
    creation: 62,
    playmaking: 56,
    rebounding: 78,
    perimeterDefense: 91,
    interiorDefense: 84,
    switchability: 94,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
  {
    playerId: 'owen-price',
    shooting: 58,
    creation: 44,
    playmaking: 52,
    rebounding: 88,
    perimeterDefense: 62,
    interiorDefense: 89,
    switchability: 68,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
  {
    playerId: 'luca-hayes',
    shooting: 73,
    creation: 60,
    playmaking: 64,
    rebounding: 61,
    perimeterDefense: 72,
    interiorDefense: 54,
    switchability: 74,
    metadata: { sourceSeason: 'fictional-demo-v1' },
  },
];
